name: CI

on:
  push:
    branches: ["main"]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Backend
      - name: Install backend
        working-directory: backend
        run: npm install

      - name: Install ESLint backend
        working-directory: backend
        run: npm install eslint --save-dev

      - name: Run backend lint
        working-directory: backend
        run: npx eslint . || true

      # Frontend
      - name: Install frontend
        working-directory: frontend
        run: npm install

      - name: Install ESLint frontend
        working-directory: frontend
        run: npm install eslint --save-dev

      - name: Run frontend lint
        working-directory: frontend
        run: npx eslint . || true